spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application: springcloud-config-dev
  name:springcloud-config-dev

---
spring:
  profiles: test
  application: springcloud-config-test
  name:springcloud-config-test
